# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml
#

# This version starts a separte job for each platform config
# in order to get around the AppVeyor limit of 60 mins per job.

# build version format
version: "{build}"

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

environment:
  matrix:
    - PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      
  PYTHON_PATH: "C:/Python35"
  PYTHON_PACKAGE_PATH: "C:/Python35/Scripts"
  CMAKE_URL: "http://cmake.org/files/v3.10/cmake-3.10.2-win64-x64.zip"
  
configuration:
 - RelStatic

branches:
  only:
    - master

install:
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\cmake > nul
  - set path=C:\cmake\bin;%path%
  - cmake --version

before_build:
  - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
  - echo.
  - echo Starting build for %APPVEYOR_REPO_NAME%
  # Install dependencies
  - python scripts/update_deps.py --dir=external
  # Get Google Test
  - git clone https://github.com/google/googletest.git external/googletest
  - cd external/googletest
  - git checkout tags/release-1.8.1
  - cd %APPVEYOR_BUILD_FOLDER%
  # Verify consistency between source file generators and output
  - echo Verifying consistency between source file generators and output
  - python scripts/generate_source.py --verify external/Vulkan-Headers/registry
  # Generate build files using CMake for the build step.
  - echo Generating CMake files for %PLATFORM%
  - mkdir build
  - cd build
  - cmake -A x64 -DVULKAN_HEADERS_INSTALL_DIR=absolute_path_to_install_dir ..
  - cmake --build .
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

build:
  parallel: true                   # enable MSBuild parallel builds
  project:  build/Vulkan-Loader.sln # path to Visual Studio solution or project
  
after_build:
- 7z a -mx9 VKLoader_%BUILD_VERSION%_%PLATFORM%.7z .\build\*
  
artifacts:
  - path: VKLoader_%BUILD_VERSION%_%PLATFORM%.7z
    name: VKLoader_%BUILD_VERSION%_%PLATFORM%  
